# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'NORMAL'), (0, 'DELETED'), (-1, 'UNKNOWN')], default=1)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('cover', models.CharField(default='', max_length=100, verbose_name='cover path')),
                ('abstract', models.CharField(max_length=100, verbose_name='abstract')),
                ('content', models.TextField(max_length=10000, verbose_name='content')),
                ('views', models.IntegerField(default=0, verbose_name='view number')),
                ('comments', models.IntegerField(default=0, verbose_name='comment number')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Channel.Channel', verbose_name='channel')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
