# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'NORMAL'), (0, 'DELETED'), (-1, 'UNKNOWN')], default=1)),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='channel name')),
                ('desc', models.CharField(max_length=10000, verbose_name='channel description')),
                ('article_num', models.BigIntegerField(default=0, verbose_name='article counts')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
    ]
