# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='img',
            field=models.CharField(default='', max_length=10000, verbose_name='channel image source'),
        ),
    ]
